[package]
name = "aeko-config-program"
description = "AEKO Config program"
documentation = "https://docs.rs/aeko-config-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
chrono = { workspace = true, features = ["default", "serde"] }
serde = { workspace = true }
serde_derive = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }

[dev-dependencies]
aeko-logger = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_config_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
