[package]
name = "aeko-sbf-rust-get-minimum-delegation"
documentation = "https://docs.rs/aeko-sbf-rust-get-minimum-delegation"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
aeko-program = { workspace = true }

[lib]
crate-type = ["cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
