[package]
name = "aeko-local-cluster"
description = "AEKO Chain, Rebuilt for SocialFi Scale"
documentation = "https://docs.rs/aeko-local-cluster"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-client = { workspace = true }
aeko-config-program = { workspace = true }
aeko-core = { workspace = true }
aeko-entry = { workspace = true }
aeko-gossip = { workspace = true }
aeko-ledger = { workspace = true }
aeko-logger = { workspace = true }
aeko-pubsub-client = { workspace = true }
aeko-quic-client = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-stake-program = { workspace = true }
aeko-streamer = { workspace = true }
aeko-thin-client = { workspace = true }
aeko-tpu-client = { workspace = true }
aeko-turbine = { workspace = true }
aeko-vote = { workspace = true }
aeko-vote-program = { workspace = true }
static_assertions = { workspace = true }
tempfile = { workspace = true }
trees = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
fs_extra = { workspace = true }
gag = { workspace = true }
serial_test = { workspace = true }
aeko-download-utils = { workspace = true }
aeko-ledger = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
