[package]
name = "aeko-sbf-rust-simulation"
description = "AEKO SBF Program Simulation Differences"
documentation = "https://docs.rs/aeko-sbf-rust-simulation"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
test-bpf = []

[dependencies]
aeko-program = { workspace = true }

[dev-dependencies]
aeko-logger = { workspace = true }
aeko-program-test = { workspace = true }
aeko-sdk = { workspace = true }
aeko-validator = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
