[package]
name = "aeko-sbf-rust-sysvar"
documentation = "https://docs.rs/aeko-sbf-rust-sysvar"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
aeko-program = { workspace = true }

[features]
test-bpf = []
dummy-for-ci-check = ["test-bpf"]

[dev-dependencies]
aeko-program-runtime = { workspace = true }
aeko-program-test = { workspace = true }
aeko-sdk = { workspace = true }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
