[package]
name = "aeko-stake-program"
description = "AEKO Stake program"
documentation = "https://docs.rs/aeko-stake-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
aeko-config-program = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
proptest = { workspace = true }
aeko-logger = { workspace = true }
test-case = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_stake_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
