[package]
name = "aeko-rpc"
description = "AEKO RPC"
documentation = "https://docs.rs/aeko-rpc"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
dashmap = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true }
jsonrpc-derive = { workspace = true }
jsonrpc-http-server = { workspace = true }
jsonrpc-pubsub = { workspace = true }
libc = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
soketto = { workspace = true }
aeko-account-decoder = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-client = { workspace = true }
aeko-entry = { workspace = true }
aeko-faucet = { workspace = true }
aeko-gossip = { workspace = true }
aeko-ledger = { workspace = true }
aeko-measure = { workspace = true }
aeko-metrics = { workspace = true }
aeko-perf = { workspace = true }
aeko-poh = { workspace = true }
aeko-rayon-threadlimit = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-send-transaction-service = { workspace = true }
aeko-stake-program = { workspace = true }
aeko-storage-bigtable = { workspace = true }
aeko-streamer = { workspace = true }
aeko-svm = { workspace = true }
aeko-tpu-client = { workspace = true }
aeko-transaction-status = { workspace = true }
aeko-version = { workspace = true }
aeko-vote = { workspace = true }
aeko-vote-program = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
stream-cancel = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["codec", "compat"] }

[dev-dependencies]
serial_test = { workspace = true }
aeko-net-utils = { workspace = true }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }
aeko-stake-program = { workspace = true }
spl-pod = { workspace = true }
symlink = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_rpc"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
