[package]
name = "aeko-thin-client"
description = "AEKO Thin Client"
documentation = "https://docs.rs/aeko-thin-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
log = { workspace = true }
rayon = { workspace = true }
aeko-connection-cache = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-sdk = { workspace = true }

[dev-dependencies]
aeko-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
