[package]
name = "aeko-validator"
description = "AEKO Chain, Rebuilt for SocialFi Scale"
documentation = "https://docs.rs/aeko-validator"
default-run = "aeko-validator"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = { workspace = true }
console = { workspace = true }
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
fd-lock = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
jsonrpc-core = { workspace = true }
jsonrpc-core-client = { workspace = true, features = ["ipc"] }
jsonrpc-derive = { workspace = true }
jsonrpc-ipc-server = { workspace = true }
lazy_static = { workspace = true }
libloading = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-clap-utils = { workspace = true }
aeko-cli-config = { workspace = true }
aeko-core = { workspace = true }
aeko-download-utils = { workspace = true }
aeko-entry = { workspace = true }
aeko-faucet = { workspace = true }
aeko-genesis-utils = { workspace = true }
aeko-geyser-plugin-interface = { workspace = true }
aeko-geyser-plugin-manager = { workspace = true }
aeko-gossip = { workspace = true }
aeko-ledger = { workspace = true }
aeko-logger = { workspace = true }
aeko-metrics = { workspace = true }
aeko-net-utils = { workspace = true }
aeko-perf = { workspace = true }
aeko-poh = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-rayon-threadlimit = { workspace = true }
aeko-rpc = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-send-transaction-service = { workspace = true }
aeko-storage-bigtable = { workspace = true }
aeko-streamer = { workspace = true }
aeko-test-validator = { workspace = true }
aeko-tpu-client = { workspace = true }
aeko-unified-scheduler-pool = { workspace = true }
aeko-version = { workspace = true }
aeko-vote-program = { workspace = true }
symlink = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
aeko-account-decoder = { workspace = true }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[target."cfg(unix)".dependencies]
libc = { workspace = true }
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
