[package]
name = "aeko-merkle-tree"
description = "Solana Merkle Tree"
documentation = "https://docs.rs/aeko-merkle-tree"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
fast-math = { workspace = true }
aeko-program = { workspace = true }

[dev-dependencies]
hex = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_merkle_tree"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

