[package]
name = "aeko-address-lookup-table-program"
description = "Solana address lookup table program"
documentation = "https://docs.rs/aeko-address-loookup-table-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bytemuck = { workspace = true }
log = { workspace = true }
num-derive = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true, features = ["derive"] }
aeko-frozen-abi = { workspace = true }
aeko-frozen-abi-macro = { workspace = true }
aeko-program = { workspace = true }
thiserror = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }

[build-dependencies]
rustc_version = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_address_lookup_table_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

