[package]
name = "aeko-compute-budget-program"
description = "AEKO Compute Budget program"
documentation = "https://docs.rs/aeko-compute-budget-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_compute_budget_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
