# This package only exists to avoid circular dependencies during cargo publish:
# aeko-bpf-loader-program -> aeko-program-test -> aeko-bpf-loader-program

[package]
name = "aeko-bpf-loader-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
aeko-bpf-loader-program = { workspace = true }
aeko-program-test = { workspace = true }
aeko-sdk = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

