[package]
name = "aeko-loader-v4-program"
description = "AEKO Loader v4 program"
documentation = "https://docs.rs/aeko-loader-v4-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
aeko-measure = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }
solana_rbpf = { workspace = true }

[dev-dependencies]
bincode = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_loader_v4_program"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

