[package]
name = "aeko-sbf-rust-param-passing-dep"
description = "AEKO SBF program written in Rust"
documentation = "https://docs.rs/aeko-sbf-rust-param-passing-dep"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
aeko-program = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
