[package]
name = "aeko-udp-client"
description = "AEKO UDP Client"
documentation = "https://docs.rs/aeko-udp-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
aeko-connection-cache = { workspace = true }
aeko-net-utils = { workspace = true }
aeko-sdk = { workspace = true }
aeko-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
