[package]
name = "aeko-store-tool"
description = "Tool to inspect append vecs"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
log = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-logger = { workspace = true }
aeko-sdk = { workspace = true }
aeko-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

