[package]
name = "aeko-notifier"
description = "Solana Notifier"
documentation = "https://docs.rs/aeko-notifier"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde_json = { workspace = true }
aeko-sdk = { workspace = true }

[lib]
name = "aeko_notifier"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

