[package]
name = "aeko-unified-scheduler-pool"
description = "The AEKO unified scheduler pool"
documentation = "https://docs.rs/aeko-unified-scheduler-pool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
crossbeam-channel = { workspace = true }
derivative = { workspace = true }
log = { workspace = true }
aeko-ledger = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-unified-scheduler-logic = { workspace = true }
aeko-vote = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
aeko-logger = { workspace = true }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }
