[package]
name = "aeko-stake-accounts"
description = "AEKO Chain, Rebuilt for SocialFi Scale"
documentation = "https://docs.rs/aeko-stake-accounts"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
aeko-clap-utils = { workspace = true }
aeko-cli-config = { workspace = true }
aeko-remote-wallet = { workspace = true, features = ["default"] }
aeko-rpc-client = { workspace = true, features = ["default"] }
aeko-rpc-client-api = { workspace = true }
aeko-sdk = { workspace = true }
aeko-stake-program = { workspace = true }
aeko-version = { workspace = true }

[dev-dependencies]
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
