[package]
name = "aeko-watchtower"
description = "AEKO Chain, Rebuilt for SocialFi Scale"
documentation = "https://docs.rs/aeko-watchtower"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
humantime = { workspace = true }
log = { workspace = true }
aeko-clap-utils = { workspace = true }
aeko-cli-config = { workspace = true }
aeko-cli-output = { workspace = true }
aeko-logger = { workspace = true }
aeko-metrics = { workspace = true }
aeko-notifier = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-sdk = { workspace = true }
aeko-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
