[package]
name = "aeko-zk-token-proof-program"
description = "AEKO ZK Token Proof program"
documentation = "https://docs.rs/aeko-zk-token-proof-program"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
num-derive = { workspace = true }
num-traits = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-zk-token-sdk = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
curve25519-dalek = { workspace = true }

[[bench]]
name = "verify_proofs"
harness = false
