[package]
name = "aeko-tokens"
description = "AEKO Chain, Rebuilt for SocialFi Scale"
documentation = "https://docs.rs/aeko-tokens"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
chrono = { workspace = true, features = ["default", "serde"] }
clap = "2.33.0"
console = { workspace = true }
csv = { workspace = true }
ctrlc = { workspace = true, features = ["termination"] }
indexmap = { workspace = true }
indicatif = { workspace = true }
pickledb = { workspace = true, features = ["yaml"] }
serde = { workspace = true, features = ["derive"] }
aeko-account-decoder = { workspace = true }
aeko-clap-utils = { workspace = true }
aeko-cli-config = { workspace = true }
aeko-remote-wallet = { workspace = true, features = ["default"] }
aeko-rpc-client = { workspace = true, features = ["default"] }
aeko-rpc-client-api = { workspace = true }
aeko-sdk = { workspace = true }
aeko-transaction-status = { workspace = true }
aeko-version = { workspace = true }
spl-associated-token-account = { workspace = true }
spl-token = { workspace = true, features = ["no-entrypoint"] }
tempfile = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
aeko-logger = { workspace = true }
aeko-streamer = { workspace = true }
aeko-test-validator = { workspace = true }
