[package]
name = "aeko-quic-client"
description = "Solana Quic Client"
documentation = "https://docs.rs/aeko-quic-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-mutex = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
quinn-proto = { workspace = true }
rustls = { workspace = true, features = ["dangerous_configuration"] }
aeko-connection-cache = { workspace = true }
aeko-measure = { workspace = true }
aeko-metrics = { workspace = true }
aeko-net-utils = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-sdk = { workspace = true }
aeko-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
crossbeam-channel = { workspace = true }
aeko-logger = { workspace = true }
aeko-perf = { workspace = true }

