[package]
name = "aeko-poh-bench"
documentation = "https://docs.rs/aeko-poh-bench"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { version = "3.1.5", features = ["cargo"] }
log = { workspace = true }
rayon = { workspace = true }
aeko-entry = { workspace = true }
aeko-logger = { workspace = true }
aeko-measure = { workspace = true }
aeko-perf = { workspace = true }
aeko-sdk = { workspace = true }
aeko-version = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

