[package]
name = "aeko-svm"
description = "AEKO SVM"
documentation = "https://docs.rs/aeko-svm"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
itertools = { workspace = true }
log = { workspace = true }
percentage = { workspace = true }
aeko-bpf-loader-program = { workspace = true }
aeko-frozen-abi = { workspace = true }
aeko-frozen-abi-macro = { workspace = true }
aeko-loader-v4-program = { workspace = true }
aeko-measure = { workspace = true }
aeko-metrics = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-system-program = { workspace = true }

[lib]
crate-type = ["lib"]
name = "aeko_svm"

[dev-dependencies]
bincode = { workspace = true }
aeko-logger = { workspace = true }
aeko-sdk = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[build-dependencies]
rustc_version = { workspace = true }

[features]
dev-context-only-utils = []
