[package]
name = "aeko-turbine"
description = "Blockchain, Rebuilt for Scale"
documentation = "https://docs.rs/aeko-turbine"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bytes = { workspace = true }
crossbeam-channel = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
lru = { workspace = true }
quinn = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = { workspace = true }
rustls = { workspace = true }
aeko-entry = { workspace = true }
aeko-gossip = { workspace = true }
aeko-ledger = { workspace = true }
aeko-measure = { workspace = true }
aeko-metrics = { workspace = true }
aeko-perf = { workspace = true }
aeko-poh = { workspace = true }
aeko-quic-client = { workspace = true }
aeko-rayon-threadlimit = { workspace = true }
aeko-rpc = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-streamer = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
aeko-logger = { workspace = true }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }
test-case = { workspace = true }

[[bench]]
name = "cluster_info"

[[bench]]
name = "cluster_nodes"

[[bench]]
name = "retransmit_stage"
