[package]
name = "aeko-wen-restart"
description = "Automatic repair and restart protocol"
documentation = "https://github.com/aeko-foundation/aeko-improvement-documents/pull/46"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }
publish = true

[dependencies]
anyhow = { workspace = true }
log = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
aeko-gossip = { workspace = true }
aeko-ledger = { workspace = true }
aeko-logger = { workspace = true }
aeko-program = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-vote-program = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
rand = { workspace = true }
serial_test = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-entry = { workspace = true }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }
aeko-streamer = { workspace = true }
tempfile = { workspace = true }

[build-dependencies]
prost-build = { workspace = true }
rustc_version = { workspace = true }

# windows users should install the protobuf compiler manually and set the PROTOC
# envar to point to the installed binary
[target."cfg(not(windows))".build-dependencies]
protobuf-src = { workspace = true }

[lib]
name = "aeko_wen_restart"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

