[package]
name = "aeko-sbf-rust-invoked"
documentation = "https://docs.rs/aeko-sbf-rust-invoked"
version = { workspace = true }
description = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
default = ["program"]
program = []

[dependencies]
aeko-program = { workspace = true }

[lib]
crate-type = ["lib", "cdylib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
