[package]
name = "aeko-tpu-client"
description = "AEKO TPU Client"
documentation = "https://docs.rs/aeko-tpu-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
async-trait = { workspace = true }
bincode = { workspace = true }
futures-util = { workspace = true }
indexmap = { workspace = true }
indicatif = { workspace = true, optional = true }
log = { workspace = true }
rayon = { workspace = true }
aeko-connection-cache = { workspace = true }
aeko-measure = { workspace = true }
aeko-metrics = { workspace = true }
aeko-pubsub-client = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-sdk = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[features]
default = ["spinner"]
# Support tpu-client methods that feature a spinner progress bar for
# command-line interfaces
spinner = ["dep:indicatif", "aeko-rpc-client/spinner"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
