[package]
name = "aeko-zk-token-proof-program-tests"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dev-dependencies]
bytemuck = { workspace = true, features = ["derive"] }
curve25519-dalek = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-program-test = { workspace = true }
aeko-sdk = { workspace = true }
aeko-zk-token-sdk = { workspace = true }
