[package]
name = "aeko-test-validator"
description = "AEKO Chain, Rebuilt for SocialFi Scale"
readme = "../README.md"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
base64 = { workspace = true }
bincode = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-cli-output = { workspace = true }
aeko-client = { workspace = true }
aeko-core = { workspace = true }
aeko-geyser-plugin-manager = { workspace = true }
aeko-gossip = { workspace = true }
aeko-ledger = { workspace = true }
aeko-logger = { workspace = true }
aeko-net-utils = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-program-test = { workspace = true }
aeko-rpc = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-streamer = { workspace = true }
aeko-tpu-client = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
