[package]
name = "aeko-net-utils"
description = "Solana Network Utilities"
documentation = "https://docs.rs/aeko-net-utils"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
clap = { version = "3.1.5", features = ["cargo"] }
crossbeam-channel = { workspace = true }
log = { workspace = true }
nix = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
socket2 = { workspace = true }
aeko-logger = { workspace = true }
aeko-sdk = { workspace = true }
aeko-version = { workspace = true }
tokio = { workspace = true, features = ["full"] }
url = { workspace = true }

[lib]
name = "aeko_net_utils"

[[bin]]
name = "aeko-ip-address"
path = "src/bin/ip_address.rs"

[[bin]]
name = "aeko-ip-address-server"
path = "src/bin/ip_address_server.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

