[package]
name = "aeko-rpc-test"
description = "AEKO RPC Test"
documentation = "https://docs.rs/aeko-rpc-test"
publish = false
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bincode = { workspace = true }
bs58 = { workspace = true }
crossbeam-channel = { workspace = true }
futures-util = { workspace = true }
log = { workspace = true }
reqwest = { workspace = true, features = ["blocking", "brotli", "deflate", "gzip", "rustls-tls", "json"] }
serde = { workspace = true }
serde_json = { workspace = true }
aeko-account-decoder = { workspace = true }
aeko-client = { workspace = true }
aeko-pubsub-client = { workspace = true }
aeko-rpc = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-rpc-client-api = { workspace = true }
aeko-sdk = { workspace = true }
aeko-streamer = { workspace = true }
aeko-test-validator = { workspace = true }
aeko-tpu-client = { workspace = true }
aeko-transaction-status = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
aeko-logger = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
