[package]
name = "aeko-ledger-tool"
description = "AEKO Chain, Rebuilt for SocialFi Scale"
documentation = "https://docs.rs/aeko-ledger-tool"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
bs58 = { workspace = true }
chrono = { workspace = true, features = ["default"] }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
csv = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
histogram = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
num_cpus = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
aeko-account-decoder = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-bpf-loader-program = { workspace = true }
aeko-clap-utils = { workspace = true }
aeko-cli-output = { workspace = true }
aeko-core = { workspace = true }
aeko-cost-model = { workspace = true }
aeko-entry = { workspace = true }
aeko-geyser-plugin-manager = { workspace = true }
aeko-gossip = { workspace = true }
aeko-ledger = { workspace = true }
aeko-logger = { workspace = true }
aeko-measure = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-rpc = { workspace = true }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }
aeko-sdk = { workspace = true }
aeko-stake-program = { workspace = true }
aeko-storage-bigtable = { workspace = true }
aeko-streamer = { workspace = true }
aeko-transaction-status = { workspace = true }
aeko-unified-scheduler-pool = { workspace = true }
aeko-version = { workspace = true }
aeko-vote-program = { workspace = true }
solana_rbpf = { workspace = true, features = ["debugger"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemallocator = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
bytecount = { workspace = true }

[features]
dev-context-only-utils = []

[target."cfg(unix)".dependencies]
signal-hook = { workspace = true }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

