[package]
description = "Solana Program Test Framework"
name = "aeko-program-test"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
assert_matches = { workspace = true }
async-trait = { workspace = true }
base64 = { workspace = true }
bincode = { workspace = true }
chrono-humanize = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
aeko-accounts-db = { workspace = true }
aeko-banks-client = { workspace = true }
aeko-banks-interface = { workspace = true }
aeko-banks-server = { workspace = true }
aeko-bpf-loader-program = { workspace = true }
aeko-logger = { workspace = true }
aeko-program-runtime = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-svm = { workspace = true }
aeko-vote-program = { workspace = true }
solana_rbpf = { workspace = true }
test-case = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
aeko-stake-program = { workspace = true }


