[package]
name = "aeko-rpc-client-nonce-utils"
description = "AEKO RPC Client Nonce Utilities"
documentation = "https://docs.rs/aeko-nonce-client"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = "2.33.0"
aeko-clap-utils = { workspace = true }
aeko-rpc-client = { workspace = true }
aeko-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
aeko-account-decoder = { workspace = true }
aeko-rpc-client-api = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

