[package]
name = "aeko-send-transaction-service"
description = "AEKO send transaction service"
documentation = "https://docs.rs/aeko-send-transaction-service"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
crossbeam-channel = { workspace = true }
log = { workspace = true }
aeko-client = { workspace = true }
aeko-measure = { workspace = true }
aeko-metrics = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
aeko-tpu-client = { workspace = true }

[dev-dependencies]
aeko-logger = { workspace = true }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
