[package]
name = "aeko-poh"
description = "Solana PoH"
documentation = "https://docs.rs/aeko-poh"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
core_affinity = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
aeko-entry = { workspace = true }
aeko-ledger = { workspace = true }
aeko-measure = { workspace = true }
aeko-metrics = { workspace = true }
aeko-runtime = { workspace = true }
aeko-sdk = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
rand = { workspace = true }
aeko-logger = { workspace = true }
aeko-perf = { workspace = true }
aeko-poh = { path = ".", features = ["dev-context-only-utils"] }
aeko-runtime = { workspace = true, features = ["dev-context-only-utils"] }

[features]
dev-context-only-utils = []

[lib]
crate-type = ["lib"]
name = "aeko_poh"

[[bench]]
name = "poh"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

